### ISSUE TITLE
Warnings thrown during standardization

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#441]
The test_dataset.py module currently is throwing a bunch of warnings, that I believe all originate from #418 

To me these look as if the test is trying to do some maths that it should not be allowed to do (log of 0, square root of negative number, divide by 0). If that is true, I am not sure why it is throwing warnings instead of errors for this.

I think we should investigate what is going on and why these warnings are being raised. If it is truly not a problem, the warnings can be suppressed or (even better) recode it in a way that the warning isn't raised in the first place.

The more "unnecessary" warnings are produced in actual use cases, the less likely it is a user will actually pay attention to the warnings that are actually relevant.

> tests/test_dataset.py::TestDataSet::test_features_transform_logic_graphdataset
>   /home/dbodor/git/DeepRank/deeprank-core/tests/test_dataset.py:823: RuntimeWarning: invalid value encountered in log
>     features_transform = {'all': {'transform': lambda t: np.log(t+10), 'standardize': True}}
> 
> tests/test_dataset.py::TestDataSet::test_only_transform_all_graphdataset
>   /home/dbodor/git/DeepRank/deeprank-core/tests/test_dataset.py:537: RuntimeWarning: invalid value encountered in log
>     features_transform = {'all': {'transform': lambda t: np.log(t+10)}}
> 
> tests/test_dataset.py::TestDataSet::test_only_transform_graphdataset
>   /home/dbodor/git/DeepRank/deeprank-core/tests/test_dataset.py:456: RuntimeWarning: invalid value encountered in sqrt
>     'electrostatic': {'transform': lambda t: np.sqrt(t+50)},
> 
> tests/test_dataset.py::TestDataSet::test_transform_standardize_graphdataset
>   /home/dbodor/git/DeepRank/deeprank-core/tests/test_dataset.py:740: RuntimeWarning: invalid value encountered in sqrt
>     'electrostatic': {'transform': lambda t: np.sqrt(t+50), 'standardize': True},
> 
> tests/test_dataset.py::TestDataSet::test_transform_standardize_graphdataset
>   /home/dbodor/git/DeepRank/deeprank-core/deeprankcore/dataset.py:783: RuntimeWarning: divide by zero encountered in true_divide
>     vals = (vals-self.means[feat])/self.devs[feat]

**Comment by DaniBodor** [comment]
BTW, i haven't looked in detail at that PR, so if it was already discussed there I haven't seen it ;)

**Comment by gcroci2** [comment]
Indeed we noticed such warnings, and we couldn't figure out why they were there. There are no 0s or numbers < 0 for log and sqrt transformations, respectively. We gave up after investigating it a bit, but she should have raised an issue about it. Good that you did!

**Comment by joyceljy** [comment]
I fixed some of the warning messages in https://github.com/DeepRank/deeprank-core/pull/442,
but there is one test(```test_only_transform_all_graphdataset```) that I can't think of a better way to fix it, so I will just leave the warning message for that one.

**Comment by joyceljy** [comment]
I tried to print out the data array directly(passing ```features_transform``` to the ```_compute_features_manually```` function in ```test_dataset.py``` file ), and print the result like this ```print(arr+10)``` before applying the ```np.log``` function.
Every value seems to be good (no 0s, no inf, no NaNs). Also ```print(np.log(arr+10))``` shows good without any warnings.
But if I use the original code that passes the ```features_transform```   to the GraphDataset Object which calls the ```hdf5_to_pandas```` function to compute the dataset, it will show the invalid value warning, which is really strange. 

I tried to search a bit on the Internet, it may be because of this issue mentioned here https://www.geeksforgeeks.org/how-to-fix-runtimewarning-invalid-value-encountered-in-double_scalars/ (Scroll down to Method2). The reason is NumPy library cannot handle this large number on so complex a structure, it will give an invalid value warning on that. Maybe our ```hdf5_to_pandas```` function is too complicated because it uses a pandas data frame? ```_compute_features_manually```` function works fine because it uses a data array instead.

I can show you the script and maybe discuss it together if my explanation is not clear enough.
But now I will suppress the warnings using the method Dani mentioned.
