### ISSUE TITLE
calculate atom pairwise energies (combination between LJ and Coulomb) using OpenMM

### ISSUE THREAD

**Issue by DaniBodor** [DeepRank/deeprank2#501]

**Comment by DaniBodor** [comment]
Currently the definition of the interface is a bit of a mess (see #460), and will be fixed by PR #492 that I am currently working on. 

In short, the atom pairs are defined by this function:
https://github.com/DeepRank/deeprank2/blob/7fdf6abdc3da78339f59eea0e937a35fe49e150f/deeprank2/utils/buildgraph.py#L166-L211

**Comment by DaniBodor** [comment]
As @cbaakman pointed out, the current feature module that calculates the nonbond energies in the "old" method is this: https://github.com/DeepRank/deeprank2/blob/main/deeprank2/features/contact.py

**Comment by joaomcteixeira** [comment]
Hi,

I see. Following the conversations on Slack, I am making the script to receive the PDB with the complex as input. Then, I calculate the interface residues by a heavy-atom distance cutoff of 5A (parameter that can be changed). Finally, it outputs a list with the atom's description, like the one below. However, I can make a function that also receives a list of residue pairs if you wish to input that instead of the complex. The same goes for the output; I can make it in any format. There are additional functionalities that I am obviating now for simplicity.

Whatever the case, I will make it a standalone script that can be used as a command-line executable or a library from which you can import the functions you may need in other contexts.

```
chain A PRO 21 CA chain B ALA 46 C -0.04088635383668866 -1.089472957596496
chain A PRO 21 CA chain B ALA 46 O -0.12798309611088915 1.292682628558653
chain A PRO 21 CA chain B ALA 46 CB -0.06765552420689089 0.35987891271055084
chain A PRO 21 C chain B ALA 46 CA -0.03856243156110351 1.347274101031214
```

**Comment by gcroci2** [comment]
This should be done in pdbprep, and its integration into deeprank2 will be handled in #509
